### ISSUE TITLE
ICRA 2016

### ISSUE THREAD

**Issue by sadmansk** [Controls-UWNRG/minotaur#15]
Be competition ready for the 2016 mobility challenge.

We will have 14 different nodes representing each intersection points on the field. Each node will have an array of adjacent nodes and will also have a hard coded path definition for each of those nodes. Only the base directional movements will be abstracted.

![icra2016_field](https://cloud.githubusercontent.com/assets/7534496/15061671/f4faa56a-1305-11e6-8eb8-d9597f70c662.PNG)

Things to be done:
- [x] Node base class
- [x] Node definitions
- [x] Path movement definitions

In terms of abstracted directional movements, these should be implemented in `movement/actuator.py`:
- [x] Straight movement (up, down, left, and right). Takes in the value to move (in mm).
- [x] Hypotenuse movement (at an angle of 60 degrees, up and down). Also takes in the move value (in mm).
- [x] Circular movement (takes in a starting angle, ending angle, and radius)

Official rules documentation: http://www1.ece.uic.edu/~paprotny/RAS_MMC_2016_Official_Rules_v1.pdf

Instead of putting this one in a milestone, it's better to have this as a issue so we can comment on it and communicate about the issues that we commit to. And also milestones don't support markdown.

Another thing, instead of creating issues, just make a PR with the branch that you are working on and add a `in progress` to the PR. And also comment here about what you will be working on.

**Comment by sadmansk** [comment]
I will take on the first task, the node definitions tasks should just be very tedious to write out. To avoid merge conflicts, for now, I will take care of the node and path tasks, and you guys can tick off the movement ones one by one.

**Comment by tammy** [comment]
I'll take on the hypotenuse movement task.

**Comment by sadmansk** [comment]
I'll work on the circular path as well
