### ISSUE TITLE
Draw borderless path on GUI

### ISSUE THREAD

**Issue by sadmansk** [Controls-UWNRG/minotaur#2]
When pressed "Ok" on the Navigate Maze window, the controls of the robot moves it along the points that are on screen while waiting for a period of time to allow the robot to move to the point. Assuming: robot starts on top left corner.

**Comment by tammy** [comment]
Currently: points and paths (connected by points) can be drawn on the screen. Reset is done with "R", but otherwise there is no limit to the amount of points drawn.
